openapi: 3.0.0
info:
  title: DevBoard
  version: 1.0.0
  description: >-
    # DevBoard API Documentation

    This project aims to create a platform where developers can share knowledge, ask questions, and earn recognition for their contributions.
  termsOfService: "http://swagger.io/terms/"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: http://localhost:8000/api/v1
    description: Localhost
  - url: https://devboard-q4gr.onrender.com/api/v1
    description: Render
tags:
  - name: Users
  - name: Blogs
  - name: Questions
  - name: Answers
  - name: Comments
  - name: Tags
  - name: Leaderboard
paths:
  /tags/create:
    post:
      tags:
        - Tags
      summary: Add new tag
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Test
                description: >-
                  A platform for developing, shipping, and running applications
                  in containers.
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /tags/list:
    get:
      tags:
        - Tags
      summary: Get by pagination
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: "1"
        - name: limit
          in: query
          schema:
            type: integer
          example: "5"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /tags/search:
    get:
      tags:
        - Tags
      summary: Search Tag
      parameters:
        - name: q
          in: query
          schema:
            type: string
          example: react
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /tags/tag/:id:
    get:
      tags:
        - Tags
      summary: Get by Id
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /tags/update/:id:
    put:
      tags:
        - Tags
      summary: Update by Id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Test.js
                description: React is JS library
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /tags/delete/:id:
    delete:
      tags:
        - Tags
      summary: Delete Tag
      responses:
        "204":
          description: Deleted successfully

  /questions/create:
    post:
      tags:
        - Questions
      summary: Create new question
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - content
                - author
              properties:
                title:
                  type: string
                  example: Test
                content:
                  type: string
                  example: >-
                    A platform for developing, shipping, and running applications
                    in containers.
                author:
                  type: string
                  example: "6662338196e7a6fedc4229f2"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /questions/author:
    get:
      tags:
        - Questions
      summary: Get questions by author Id with pagination, default limit is 5
      parameters:
        - name: author
          in: query
          schema:
            type: string
          example: "6655a5ec7e7e084884bff451"
        - name: page
          in: query
          schema:
            type: integer
          example: "1"
        - name: limit
          in: query
          schema:
            type: integer
          example: "5"
        - name: sort
          in: query
          schema:
            type: string
            enum:
              - created_at
              - -created_at
              - title
              - -title
          example: "-created_at"
          description: Sort order (ascending or descending)
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /questions/list:
    get:
      tags:
        - Questions
      summary: Get questions with pagination, default limit is 5
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: "1"
        - name: limit
          in: query
          schema:
            type: integer
          example: "5"
        - name: sort
          in: query
          schema:
            type: string
            enum:
              - created_at
              - -created_at
              - title
              - -title
          example: "-created_at"
          description: Sort order (ascending or descending)
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /questions/search:
    get:
      tags:
        - Questions
      summary: Search Question
      parameters:
        - name: q
          in: query
          schema:
            type: string
          example: react
        - name: page
          in: query
          schema:
            type: integer
          example: "1"
        - name: limit
          in: query
          schema:
            type: integer
          example: "5"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /questions/question/{id}:
    get:
      tags:
        - Questions
      summary: Get by Id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: "6661c0c61039e9d27f5dc64f"
          description: The ID of the question to retrieve
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /questions/update/{id}:
    put:
      tags:
        - Questions
      summary: Update by Id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: "6655a5ec7e7e084884bff451"
          description: The ID of the question to update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Test
                content: >-
                  A platform for developing, shipping, and running applications
                  in containers.
                tags: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /questions/delete/{id}:
    delete:
      tags:
        - Questions
      summary: Delete Question
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: "6655a5ec7e7e084884bff451"
          description: The ID of the question to delete
      responses:
        "204":
          description: Deleted successfully

  /users/register:
    post:
      tags:
        - Users
      summary: Register new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                  example: John
                email:
                  type: string
  /users/login:
    post:
      tags:
        - Users
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: 8WpQr@example.com
  /users/logout:
    post:
      tags:
        - Users
      summary: Logout
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users/user:
    get:
      tags:
        - Users
      summary: Get user by username or email or id
      parameters:
        - name: username
          in: query
          schema:
            type: string
          example: "algoavatar"
        - name: id
          in: query
          schema:
            type: string
          example: "6655a5ec7e7e084884bff451"
        - name: email
          in: query
          schema:
            type: string
          example: "teamalgoavatar@gmail.com"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users/list:
    get:
      tags:
        - Users
      summary: Get users with pagination, default limit is 5
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: "1"
        - name: limit
          in: query
          schema:
            type: integer
          example: "5"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users/update/{id}:
    put:
      tags:
        - Users
      summary: Update by Id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: "6655a5ec7e7e084884bff451"
          description: The ID of the user to update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: John
                email: 8WpQr@example.com
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users/delete/{id}:
    delete:
      tags:
        - Users
      summary: Delete User
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: "6655a5ec7e7e084884bff451"
          description: The ID of the user to delete
      responses:
        "204":
          description: Deleted successfully

  /blogs/list:
    get:
      tags:
        - Blogs
      summary: Get blogs with pagination, default limit is 5
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: "1"
        - name: limit
          in: query
          schema:
            type: integer
          example: "5"
        - name: sort
          in: query
          schema:
            type: string
            enum:
              - published_at
              - -published_at
              - title
              - -title
          example: "-published_at"
          description: Sort order (ascending or descending)
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /blogs/create:
    post:
      tags:
        - Blogs
      summary: Create new blog
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Test
                content: >-
                  A platform for developing, shipping, and running applications
                  in containers.
                author: "6655a5ec7e7e084884bff451"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /blogs/search:
    get:
      tags:
        - Blogs
      summary: Search blogs
      parameters:
        - name: q
          in: query
          schema:
            type: string
          example: "Blog"
          description: The query string
        - name: page
          in: query
          schema:
            type: integer
          example: "1"
        - name: limit
          in: query
          schema:
            type: integer
          example: "5"
        - name: sort
          in: query
          schema:
            type: string
            enum:
              - published_at
              - -published_at
              - title
              - -title
          example: "-published_at"
          description: Sort order (ascending or descending)
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /blogs/blog/{id}:
    get:
      tags:
        - Blogs
      summary: Get by Id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: "6666128ca9e652d582b47063"
          description: The ID of the blog to retrieve
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /blogs/author/{id}:
    get:
      tags:
        - Blogs
      summary: Get by author
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: "6655a5ec7e7e084884bff451"
          description: The ID of the author to retrieve
        - name: page
          in: query
          schema:
            type: integer
          example: "1"
        - name: limit
          in: query
          schema:
            type: integer
          example: "5"
        - name: sort
          in: query
          schema:
            type: string
            enum:
              - published_at
              - -published_at
              - title
              - -title
          example: "-published_at"
          description: Sort order (ascending or descending)
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /blogs/tag/{id}:
    get:
      tags:
        - Blogs
      summary: Get by tag
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: "6655d585a81fca3dcf93e10d"
          description: The ID of the tag to retrieve
        - name: page
          in: query
          schema:
            type: integer
          example: "1"
        - name: limit
          in: query
          schema:
            type: integer
          example: "5"
        - name: sort
          in: query
          schema:
            type: string
            enum:
              - published_at
              - -published_at
              - title
              - -title
          example: "-published_at"
          description: Sort order (ascending or descending)
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /blogs/update/{id}:
    put:
      tags:
        - Blogs
      summary: Update by Id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: "6655a5ec7e7e084884bff451"
          description: The ID of the blog to update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Test
                content: >-
                  A platform for developing, shipping, and running applications
                  in containers.
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /blogs/delete/{id}:
    delete:
      tags:
        - Blogs
      summary: Delete by Id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: "6655a5ec7e7e084884bff451"
          description: The ID of the blog to delete
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
